### PR TITLE
Update examples to more expected pinout

### LINKED ISSUE #41: Update example for more common pins?
Re this thread:
https://forums.adafruit.com/viewtopic.php?f=60&t=189733

The `max7219_simpletest.py` example is using `board.TX` for `MOSI`, `board.RX` for `SCLK`, and `board.A1` for `CS`. Might have been written for a specific board? But there's no associated guide AFAICT, so wiring is only documented by the code. Might be better to use actual SPI pins?

### PR DESCRIPTION
**Pull request by tekktrik**
Resolves #41 by updating examples to use a more expected pinout

### CODE REVIEW

**Comment by caternuson** [comment]
Oh yah, and the other examples as well. Thanks.

I think `board.SCK` is the typical name for the SPI clock pin. But how about changing to use `board.SPI()`:
```python
matrix = matrices.Matrix8x8(board.SPI(), cs)
```

That way, don't even need to `import busio`. This example was probably written before `board.SPI()` was added.

**Comment by tekktrik** [comment]
Ah got it, will do!

**Comment by tekktrik** [comment]
Alright @caternuson I changed them all to use `board.SPI()`

**Comment by caternuson** [comment]
Yep. OK, a couple more suggestions:
* Please update Usage Example in README.rst - I think OK to just say something like "see examples" instead of updating code listing.
* This comment line in each example is worded poorly:
```
 # You may need to change the chip select board depending on your wiring
 ```
 I think just change "board" to "pin"?

**Comment by tekktrik** [comment]
Whoops, good catch on the comment!

**Review by caternuson — APPROVED** [review]

**Comment by caternuson** [comment]
Thanks!

**Pull request merged**
