### PR TITLE
Add rotation function to max7219.py

### PR DESCRIPTION
**Pull request by bluejazzCHN**
using this function can change the **direction** of display of LED matrices

### CODE REVIEW

**Comment by ladyada** [comment]
@deshipu wanna test it out?

**Comment by jposada202020** [comment]
@bluejazzCHN Would you mind if we could make at least pass the CI this PR also? :)
Thanks

**Comment by bluejazzCHN** [comment]
> @bluejazzCHN Would you mind if we could make at least pass the CI this PR also? :)
> Thanks

it's OK. do as you think.

**Comment by jposada202020** [comment]
I made the changes in your repo via PR as you do not have a tracked branch. Thanks

**Comment by bluejazzCHN** [comment]
@jposada202020  i accepted pull from you, please check the result.

**Comment by jposada202020** [comment]
@bluejazzCHN yes thanks, we have two options:
1. that you push the changes here
2. Make a new PR. (If this it the preferred way could you make a branch, this allows contributor and maintainer to work in the same branch and would facilitate the process in cases like this, as mentioned here https://learn.adafruit.com/contribute-to-circuitpython-with-git-and-github/always-work-on-a-branch

At this stage both options are ok, whatever is easier for you :) thanks

**Comment by FoamyGuy** [comment]
Thanks for working on this @bluejazzCHN. It wasn't passing the CI checks still. But we have had a very similar feature introduced by #37 with an adaptable custom chained matrix feature. Closing this for now. Please feel free to make a new PR if you want to modify the current version.

**Pull request closed without merging**
