### PR TITLE
Make BCDDigits chainable

### LINKED ISSUE #39: Cascade several 7-segment display modules
is it possible to use (cascade) multiple max7219 7-segment display modules?

### PR DESCRIPTION
**Pull request by tekktrik**
Not tested.

Resolves #39 by changing inheritance of `BCDDigits` to `ChainableMAX7219`.  Also adds a value check to notify if a digit is ever out of range.

### CODE REVIEW

**Comment by FoamyGuy** [comment]
@bschymanski is this new functionality something you have the hardware to test?

**Comment by bschymanski** [comment]
> i will download the new code and will test this with two daisychained MAX7219 hopefully tomorrow

**Comment by tekktrik** [comment]
I actually ordered something to help with this, but mail is turtle-pace right now, converting to draft in the meantime.  I'll re-convert when I get it and finalize this PR.

**Comment by tekktrik** [comment]
Hardware arrived, now I just need to figure out which moving box has my soldering equipment >:(

**Comment by tekktrik** [comment]
Pros:  I have the prototype working!
Cons:  It's not working _as intended_, chances are this will take me a while!

**Comment by FlantasticDan** [comment]
@tekktrik Glad to see someone is taking this up, I think you might be in a similar place where I left off.  I tried to get chained BCD Digits working after I implemented `ChainableMAX7219` in #37 but found that it would require some reworking of the existing BCD implementation I wasn't prepared to undertake.

I have the hardware to test when you're ready or if you need some help!

**Comment by tekktrik** [comment]
Unfortunately, I think I'm going to close this for now since I haven't had time to work on and don't know when I will.  I'll keep the branch though, and hopefully I'll be able to come back to this.

**Pull request closed without merging**
