### PR TITLE
Adding adafruit-circuitpython-framebuf

### PR DESCRIPTION
**Pull request by Tasm-Devil**

### CODE REVIEW

**Comment by ladyada** [comment]
@Tasm-Devil awesome, thank you :) did you try it with hardware?

**Comment by Tasm-Devil** [comment]
Yes. Tried it on an nrf52840 with CP4 and it works.

**Comment by ladyada** [comment]
its not working because we dont have `scroll` in adafruit_framebuf...not sure when we'll get to implementing it :(

**Comment by Tasm-Devil** [comment]
I (re)implemented the scroll method to adafruit_framebuff. Now it works. I tested it.

**Comment by ladyada** [comment]
huzzzah - i did a release so in a bit ill rerun travis!

**Comment by ladyada** [comment]
hmm its still failing, but it could be a pylint bug - did you try the simpletest.py example?

**Comment by Tasm-Devil** [comment]
I tested `max7219_simpletest.py` and `framebuf_simpletest.py`.
Both work with no problems on the nrf52840.
I have no Linux-Circuitpython installation. So I can't test this one.

It sounds like Travis is using the _previous_ Version of adafruit-circuitpython-framebuf which has a scroll-method with no arguments. That's where the **Too many positional arguments for method call (too-many-function-args)** Error comes from.

**Comment by ladyada** [comment]
weird -  it was another error --- but now it works :)

**Pull request merged**
